Repository acm-ucr/cse-ula, pull requests merged in 2025-08, with the labels that each got.

#96 Button Link to Homepage
  src/components/Navbar.tsx
Labels: ready for review

#97 Animated 'Our Goals' component
  src/components/about/OurGoals.tsx
  src/components/about/OurGoalsCard.tsx
Labels: ready for review

#84 Course Offerings Responsiveness Layout
  src/components/about/CourseOfferingCard.tsx
  src/components/about/CourseOfferings.tsx
Labels: ready for review

#99 Footer mobile responsify
  src/components/Footer.tsx
Labels: ready for review, changes requested

#114 Fixed mobile responsiveness and added an animation
  src/components/ula/Card.tsx
  src/components/ula/MeetULAS.tsx
  src/components/ula/OurULAS.tsx
Labels: ready for review

#115 just a lil fix
  src/components/Navbar.tsx
Labels: ready for review

#111 404/500 Errors Mobile Responsiveness
  src/components/ErrorMessage.tsx
Labels: ready for review

#113 Landing Page Animation REVISED
  src/components/home/Landing.tsx
Labels: changes requested

#94 Gutlapallin/prof animation
  package-lock.json
  package.json
  src/components/about/Professor.tsx
Labels: changes requested

#123 Citations Section Animation
  src/components/about/Citations.tsx
Labels: ready for review

#134 Added images animation
  src/components/home/Images.tsx
Labels: ready for review

#145 Overflow Bug Mobile
  src/app/layout.tsx
Labels: ready for review

#141 Added flipping to course offerings
  src/components/about/CourseOfferingCard.tsx
  src/components/about/CourseOfferings.tsx
  src/data/CourseOfferings.ts
Labels: ready for review

#133 404 Animation
  src/components/ErrorMessage.tsx
  src/components/home/InfoBanner.tsx
Labels: changes requested

#156 Browse to courses
  src/components/about/CourseOfferings.tsx
  src/components/home/Questions.tsx
Labels: ready for review

#155 Boweser Side Image Loading Bug
  src/components/about/Professor.tsx
Labels: ready for review

#146 Animated images: slide-in from left with staggered delays
  src/components/home/Images.tsx
Labels: ready for review, changes requested
